# Generated by Django 6.0.1 on 2026-02-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
