# Generated by Django 6.0.1 on 2026-02-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_delete_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='employee_faces/'),
        ),
    ]
