# Generated by Django 6.0.1 on 2026-02-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_employee_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
    ]
